Internal Server Error: /live_game_blog/past_games/
Traceback (most recent call last):
  File "/home/carl/projects/iubase/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/carl/projects/iubase/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/carl/projects/iubase/live_game_blog/views.py", line 38, in past_games
    raise ValueError("Logging Test Only")
ValueError: Logging Test Only
Internal Server Error: /live_game_blog/past_games/
Traceback (most recent call last):
  File "/home/carl/projects/iubase/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/carl/projects/iubase/.venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/carl/projects/iubase/live_game_blog/views.py", line 38, in past_games
    raise ValueError("Logging Test Only")
ValueError: Logging Test Only
